### PR TITLE
fixes server-rendered getServerSnapshot requirement

### LINKED ISSUE #2: Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
### Steps to Replicate
* App/page must be server-rendered
* Open app and this error will show

### Screenshot
Screen Shot 2022-10-23 at 1 08 54 PM

### PR DESCRIPTION
**Pull request by carledwardfp**
* fixes server-rendered getServerSnapshot requirement

#### Closes #2

### CODE REVIEW

File: fast-context-generic/src/createFastContext.tsx [hunk 1]
```diff
@@ -55,8 +55,10 @@ export default function createFastContext<Store>(initialState: Store) {
       throw new Error("Store not found");
     }
 
-    const state = useSyncExternalStore(store.subscribe, () =>
-      selector(store.get())
+    const state = useSyncExternalStore(
+      store.subscribe,
+      () => selector(store.get()),
+      () => selector(store.get()),
```
Comment (jherr) [inline fast-context-generic/src/createFastContext.tsx]: I think it should be `() => initialState` since the initial state is what we get from the server and in the docs for this hook the requirement is that you always return the same reference from `getServerSnapshot`.

**Review by jherr — COMMENTED** [review]
Needs a tweak to the implementation.

File: fast-context-generic/src/createFastContext.tsx (hunk 1 above)
Comment (himsog) [reply fast-context-generic/src/createFastContext.tsx:61]: Or should it be `() => selector(initialState)`  to get the actual field?

Comment (carledwardfp) [reply fast-context-generic/src/createFastContext.tsx]: Thanks you're right. Should it be `() => selector(initialState)`?

Comment (jherr) [reply fast-context-generic/src/createFastContext.tsx]: Ah, yes, true, the selector needs to be there. Alright, good fix, let's add it.

Comment (carledwardfp) [reply fast-context-generic/src/createFastContext.tsx]: Fixed the PR. Thank you!
